import re
from datetime import datetime
from typing import Any

from config import (
    API_SNAPSHOT_URL,
    API_TIMEOUT_SECONDS,
    HISTORIAN_DB_WINDER_AUX_BIT,
    HISTORIAN_DB_WINDER_NUM,
    HISTORIAN_DB_WINDER_START_BIT,
    HISTORIAN_DB_WINDER_STATUS_BYTE,
    HISTORIAN_DOWNTIME_ROLLNAME,
    HISTORIAN_EVENT_HOLDOFF_MS,
    HISTORIAN_EXTRA_FUNCTIONS,
    HISTORIAN_INTERVAL_MS,
    HISTORIAN_MARKER_FIRST_CYCLE_BIT,
    HISTORIAN_MASTER_NAME,
    HISTORIAN_MARKER_STATUS_BYTE,
    PLC_FLUCT_SCL_PATH,
    PLC_IP,
    PLC_RACK,
    PLC_SLOT,
    get_postgres_config,
)


RACK = PLC_RACK
SLOT = PLC_SLOT

DB_WINDER_NUM = HISTORIAN_DB_WINDER_NUM
DB_WINDER_STATUS_BYTE = HISTORIAN_DB_WINDER_STATUS_BYTE
DB_WINDER_START_BIT = HISTORIAN_DB_WINDER_START_BIT
DB_WINDER_AUX_BIT = HISTORIAN_DB_WINDER_AUX_BIT
DB330_NUM = DB_WINDER_NUM
DB330_STATUS_BYTE = DB_WINDER_STATUS_BYTE
DB330_START_BIT = DB_WINDER_START_BIT
DB330_AUX_BIT = DB_WINDER_AUX_BIT
MARKER_STATUS_BYTE = HISTORIAN_MARKER_STATUS_BYTE
MARKER_FIRST_CYCLE_BIT = HISTORIAN_MARKER_FIRST_CYCLE_BIT

SCL_SOURCE_PATH = PLC_FLUCT_SCL_PATH
PLC_API_SNAPSHOT_URL = API_SNAPSHOT_URL
PLC_API_TIMEOUT_SECONDS = API_TIMEOUT_SECONDS

DEFAULT_INTERVAL_MS = HISTORIAN_INTERVAL_MS
DEFAULT_EVENT_HOLDOFF_MS = HISTORIAN_EVENT_HOLDOFF_MS
DOWNTIME_ROLLNAME = HISTORIAN_DOWNTIME_ROLLNAME

FUNCTION_BODY_RE = r'(FUNCTION(?:_BLOCK)?\s+"{name}".*?BEGIN)(?P<body>.*?)(END_FUNCTION(?:_BLOCK)?)'
MASTER_NAME = HISTORIAN_MASTER_NAME
EXTRA_FLUCTUATION_FUNCTIONS = HISTORIAN_EXTRA_FUNCTIONS
MASTER_CALL_RE = re.compile(r'"(?P<name>FC_Fluct_[^"]+)"\s*\(')
SYMBOL_TOKEN_RE = re.compile(r'"([^"]+)"|([A-Za-z_][A-Za-z0-9_]*)|(\[[0-9]+\])')


def db_config() -> dict[str, Any]:
    return get_postgres_config()


def normalize_text(value: Any) -> str:
    return str(value or "").strip()


def build_rollname(now: datetime) -> str:
    return now.strftime("A %y%m%d %H%M")
